### ISSUE TITLE
Add reactive option to on_pre_player_died

### ISSUE THREAD

**Issue by plague006** [muppet9010/Factorio-Splatter-Guard#4]
Haven't looked through the code much, but from what I understand it's running every tick? Maybe consider something that triggers on_pre_player_died instead to lower the impact of your mod?

**Comment by muppet9010** [comment]
When I started this I didn't realise that you could override players health on the death event to avoid death. I'll add it as an option between preemptive jumping and death avoidance jumping.

**Comment by muppet9010** [comment]
done in 0.1.1 under 5f25d9e
