### ISSUE TITLE
Error when running on_load

### ISSUE THREAD

**Issue by coderpatsy** [muppet9010/Factorio-Splatter-Guard#8]
Just updated, and I got this error trying to load an existing map:

> Error while running on_load:
> \_\_splatter\_guard\_\_/scripts/train_jumper.lua:98:
> attempt to index global 'ModSettings' (a nil value)

Loading a new map seems to work fine.

**Comment by muppet9010** [comment]
Can I have a copy of your save and mod folder please.
I don't have any issues on changing from a 0.1.0 version save up to 0.1.1 with my test save.

**Comment by muppet9010** [comment]
don't worry, I've reproduced it

**Comment by muppet9010** [comment]
resolved in 0.1.2 under 4950053df567e118648dca9a36505dd7a08b188a
0.1.2 released immediately

inclusion in OnLoad was a mistake from my development & testing
